apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-token
  namespace: flux-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: telegram-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "shared/telegram"
        property: "token"
