apiVersion: apps/v1
kind: Deployment
metadata:
  name: shisha-frontend
  namespace: shisha-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shisha-frontend
  template:
    metadata:
      labels:
        app: shisha-frontend
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: shisha-frontend
          image: harbor.api-api-api.com/shisha/frontend:main-9-538ae01c19809f5ffffa16e4763b75b953c5d689 # {"$imagepolicy": "flux-system:shisha-frontend"}
          ports:
            - containerPort: 80
