apiVersion: apps/v1
kind: Deployment
metadata:
  name: shisha-frontend
  namespace: shisha-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shisha-frontend
  template:
    metadata:
      labels:
        app: shisha-frontend
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: shisha-frontend
          image: harbor.api-api-api.com/shisha/frontend:main-10-3bf51b3c2d47eb96ac790c12dccc8bd9a4264a95 # {"$imagepolicy": "flux-system:shisha-frontend"}
          ports:
            - containerPort: 80
