apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: shisha-frontend
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: flux@anomaly51
      messageTemplate: 'chore: update shisha-frontend image to {{range .Updated.Images}}{{.}}{{end}}'
    push:
      branch: main
  update:
    path: ./apps/shisha-frontend
    strategy: Setters
