apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-image-pull-secret
  namespace: flux-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-image-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"harbor.api-api-api.com":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: "shared/harbor"
        property: "username"
    - secretKey: password
      remoteRef:
        key: "shared/harbor"
        property: "password"
