apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-frontend
  namespace: online-shop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-shop-frontend
  template:
    metadata:
      labels:
        app: online-shop-frontend
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: online-shop-frontend
          image: harbor.api-api-api.com/online-shop/frontend:main-5-4a8436b92412aca5c79a3a389c3cc0b001e97808 # {"$imagepolicy": "flux-system:online-shop-frontend"}
          ports:
            - containerPort: 80
