apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: online-shop-backend
  namespace: flux-system
spec:
  image: harbor.api-api-api.com/online-shop/backend
  interval: 1m
  secretRef:
    name: harbor-image-pull-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: online-shop-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: online-shop-backend
  filterTags:
    pattern: '^main-(?P<build>[0-9]+)-.*$'
    extract: '$build'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: online-shop-backend
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: flux@anomaly51
      messageTemplate: "chore: update online-shop-backend image"
    push:
      branch: main
  update:
    path: ./apps/online-shop
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: online-shop-frontend
  namespace: flux-system
spec:
  image: harbor.api-api-api.com/online-shop/frontend
  interval: 1m
  secretRef:
    name: harbor-image-pull-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: online-shop-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: online-shop-frontend
  filterTags:
    pattern: '^main-(?P<build>[0-9]+)-.*$'
    extract: '$build'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: online-shop-frontend
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxbot
        email: flux@anomaly51
      messageTemplate: "chore: update online-shop-frontend image"
    push:
      branch: main
  update:
    path: ./apps/online-shop
    strategy: Setters
